import { int, mysqlEnum, mysqlTable, text, timestamp, varchar, json, boolean } from "drizzle-orm/mysql-core";

export const users = mysqlTable("users", {
  id: int("id").autoincrement().primaryKey(), openId: varchar("openId", { length: 64 }).notNull().unique(), name: text("name"), email: varchar("email", { length: 320 }), loginMethod: varchar("loginMethod", { length: 64 }), role: mysqlEnum("role", ["user", "admin"]).default("user").notNull(), preferences: json("preferences"), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull(), lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(),
});
export const categories = mysqlTable("categories", { id: int("id").autoincrement().primaryKey(), name: varchar("name", { length: 120 }).notNull().unique(), slug: varchar("slug", { length: 140 }).notNull().unique(), createdAt: timestamp("createdAt").defaultNow().notNull() });
export const ingredients = mysqlTable("ingredients", { id: int("id").autoincrement().primaryKey(), name: varchar("name", { length: 120 }).notNull().unique(), category: varchar("category", { length: 80 }), aliases: json("aliases"), createdAt: timestamp("createdAt").defaultNow().notNull() });
export const recipes = mysqlTable("recipes", { id: int("id").autoincrement().primaryKey(), title: varchar("title", { length: 220 }).notNull(), slug: varchar("slug", { length: 240 }).notNull().unique(), description: text("description"), image: text("image"), categoryId: int("categoryId"), mealType: varchar("mealType", { length: 80 }), ingredients: json("ingredients").notNull(), instructions: json("instructions").notNull(), tips: text("tips"), substitutions: text("substitutions"), prepTime: int("prepTime").notNull(), cookTime: int("cookTime").notNull(), totalTime: int("totalTime").notNull(), difficulty: mysqlEnum("difficulty", ["Fácil", "Média", "Avançada"]).default("Fácil").notNull(), servings: int("servings").default(2).notNull(), calories: int("calories"), protein: int("protein"), carbs: int("carbs"), fat: int("fat"), tags: json("tags"), allergens: json("allergens"), published: boolean("published").default(true).notNull(), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull() });
export const favorites = mysqlTable("favorites", { id: int("id").autoincrement().primaryKey(), userId: int("userId").notNull(), recipeId: int("recipeId").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull() });
export const shoppingLists = mysqlTable("shopping_lists", { id: int("id").autoincrement().primaryKey(), userId: int("userId").notNull(), items: json("items").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull() });
export const mealPlans = mysqlTable("meal_plans", { id: int("id").autoincrement().primaryKey(), userId: int("userId").notNull(), week: varchar("week", { length: 12 }).notNull(), meals: json("meals").notNull(), settings: json("settings"), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().onUpdateNow().notNull() });
export const aiRequests = mysqlTable("ai_requests", { id: int("id").autoincrement().primaryKey(), userId: int("userId"), type: varchar("type", { length: 60 }).notNull(), input: text("input").notNull(), output: text("output"), createdAt: timestamp("createdAt").defaultNow().notNull() });
export const subscriptions = mysqlTable("subscriptions", { id: int("id").autoincrement().primaryKey(), userId: int("userId").notNull(), plan: varchar("plan", { length: 40 }).default("free").notNull(), status: varchar("status", { length: 40 }).default("active").notNull(), startDate: timestamp("startDate"), expiryDate: timestamp("expiryDate"), createdAt: timestamp("createdAt").defaultNow().notNull() });

export type User = typeof users.$inferSelect; export type InsertUser = typeof users.$inferInsert;
export type Recipe = typeof recipes.$inferSelect; export type InsertRecipe = typeof recipes.$inferInsert;
